export const ActionTypes = {

    // CartItemInfo Reducer Action
    SET_CART_PRODUCTS_VALUE : "SET_CART_PRODUCT_VALUE",
    SET_CART_PRODUCT_ITEMS : "SET_CART_PRODUCT_ITEMS",

    //AuthenticationInfo Reducer Action
    SET_AUTHENTICATION_STATE : "SET_AUTHENTICATION_STATE",
    SET_USER_ACCESS_TOKEN : "SET_USER_ACCESS_TOKEN"
};

// export const SET_AUTHENTICATION_STATE = "SET_AUTHENTICATION_STATE";